sudo: false
language: go
git:
    depth: 1
install:
    # - go mod init cxyblog 
    # - go get -v github.com/gohugoio/hugo@v0.56.3
    - wget https://github.com/gohugoio/hugo/releases/download/v0.56.3/hugo_0.56.3_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
script:
    hugo
deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
    local_dir: public
    repo: xychen/xychen.github.io
    fqdn: <custom-domain-if-needed>
    target_branch: master
    email: cxybjfu@126.com
    name: xychen